In [ ]:
#importing necessary packages
import pandas as pd
import numpy as np
import warnings

In [ ]:
#importing dataset
df=pd.read_csv('/content/penguins_size.csv')
df.head()

species     island  culmen_length_mm  culmen_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen              39.1             18.7              181.0   
1  Adelie  Torgersen              39.5             17.4              186.0   
2  Adelie  Torgersen              40.3             18.0              195.0   
3  Adelie  Torgersen               NaN              NaN                NaN   
4  Adelie  Torgersen              36.7             19.3              193.0   

   body_mass_g     sex  
0       3750.0    MALE  
1       3800.0  FEMALE  
2       3250.0  FEMALE  
3          NaN     NaN  
4       3450.0  FEMALE

In [ ]:
#calculating quartile range for Culmen_length_mm column
Q1 = df['culmen_length_mm'].quantile(0.25)
Q3 = df['culmen_length_mm'].quantile(0.75)
IQR = Q3 - Q1
print(IQR)

# Define the lower and upper bounds to detect outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[(df['culmen_length_mm'] < lower_bound) | (df['culmen_length_mm'] > upper_bound)]

print("Rows containing outliers in 'culmen_length_mm':")
print(outliers)
#culmen length  column is free from outliers

9.274999999999999
Rows containing outliers in 'culmen_length_mm':
Empty DataFrame
Columns: [species, island, culmen_length_mm, culmen_depth_mm, flipper_length_mm, body_mass_g, sex]
Index: []


In [ ]:
#calculating quartile range for culmen_depth_mm column
Q1 = df['culmen_depth_mm'].quantile(0.25)
Q3 = df['culmen_depth_mm'].quantile(0.75)
IQR = Q3 - Q1
print(IQR)

# Define the lower and upper bounds to detect outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[(df['culmen_depth_mm'] < lower_bound) | (df['culmen_depth_mm'] > upper_bound)]

print("Rows containing outliers in 'culmen_depth_mm':")
print(outliers)
#culmen depth  column is free from outliers

3.0999999999999996
Rows containing outliers in 'culmen_depth_mm':
Empty DataFrame
Columns: [species, island, culmen_length_mm, culmen_depth_mm, flipper_length_mm, body_mass_g, sex]
Index: []


In [ ]:
#calculating quartile range for flipper_length_mm column
Q1 = df['flipper_length_mm'].quantile(0.25)
Q3 = df['flipper_length_mm'].quantile(0.75)
IQR = Q3 - Q1
print(IQR)

# Define the lower and upper bounds to detect outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[(df['flipper_length_mm'] < lower_bound) | (df['flipper_length_mm'] > upper_bound)]

print("Rows containing outliers in 'flipper_length_mm':")
print(outliers)
#flipper length column is free from outliers

23.0
Rows containing outliers in 'flipper_length_mm':
Empty DataFrame
Columns: [species, island, culmen_length_mm, culmen_depth_mm, flipper_length_mm, body_mass_g, sex]
Index: []


In [ ]:
#calculating quartile range for body_mass_g column
Q1 = df['body_mass_g'].quantile(0.25)
Q3 = df['body_mass_g'].quantile(0.75)
IQR = Q3 - Q1
print(IQR)

# Define the lower and upper bounds to detect outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[(df['body_mass_g'] < lower_bound) | (df['body_mass_g'] > upper_bound)]

print("Rows containing outliers in 'body_mass_g':")
print(outliers)
#body mass column is free from outliers

1200.0
Rows containing outliers in 'body_mass_g':
Empty DataFrame
Columns: [species, island, culmen_length_mm, culmen_depth_mm, flipper_length_mm, body_mass_g, sex]
Index: []


# **Data cleaning**

In [ ]:
#checking for null values
df.isnull().sum()

species               0
island                0
culmen_length_mm      2
culmen_depth_mm       2
flipper_length_mm     2
body_mass_g           2
sex                  10
dtype: int64

##**Handling missing values for numerical columns**

In [ ]:
#replacing culmen_length_mm, culmen_depth_mm, flipper_length_mm, body_mass_g
df['culmen_length_mm'].fillna(df['culmen_length_mm'].mean(), inplace=True)
df['culmen_depth_mm'].fillna(df['culmen_depth_mm'].mean(), inplace=True)
df['flipper_length_mm'].fillna(df['flipper_length_mm'].mean(), inplace=True)
df['body_mass_g'].fillna(df['body_mass_g'].mean(), inplace=True)


# **Handling missing values for categorical column 'sex'**

In [ ]:
#here we replace missing value with most frequent value in sex column
df['sex'].fillna(df['sex'].mode()[0], inplace=True)

In [ ]:
df.isnull().sum()#hence data is cleaned

species              0
island               0
culmen_length_mm     0
culmen_depth_mm      0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [ ]:
df.head()

species     island  culmen_length_mm  culmen_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen          39.10000         18.70000         181.000000   
1  Adelie  Torgersen          39.50000         17.40000         186.000000   
2  Adelie  Torgersen          40.30000         18.00000         195.000000   
3  Adelie  Torgersen          43.92193         17.15117         200.915205   
4  Adelie  Torgersen          36.70000         19.30000         193.000000   

   body_mass_g     sex  
0  3750.000000    MALE  
1  3800.000000  FEMALE  
2  3250.000000  FEMALE  
3  4201.754386    MALE  
4  3450.000000  FEMALE

In [ ]:
#checking for unique value from espective column
print(df['species'].unique())
print(df['island'].unique())
print(df['sex'].unique())

['Adelie' 'Chinstrap' 'Gentoo']
['Torgersen' 'Biscoe' 'Dream']
['MALE' 'FEMALE' '.']


# **Deciding dependent and independent variable**

In [ ]:
x=df.iloc[:,0:6]#independent variable
x

species     island  culmen_length_mm  culmen_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen          39.10000         18.70000         181.000000   
1    Adelie  Torgersen          39.50000         17.40000         186.000000   
2    Adelie  Torgersen          40.30000         18.00000         195.000000   
3    Adelie  Torgersen          43.92193         17.15117         200.915205   
4    Adelie  Torgersen          36.70000         19.30000         193.000000   
..      ...        ...               ...              ...                ...   
339  Gentoo     Biscoe          43.92193         17.15117         200.915205   
340  Gentoo     Biscoe          46.80000         14.30000         215.000000   
341  Gentoo     Biscoe          50.40000         15.70000         222.000000   
342  Gentoo     Biscoe          45.20000         14.80000         212.000000   
343  Gentoo     Biscoe          49.90000         16.10000         213.000000   

     body_mass_g  
0    3750.000000  
1    3800.000000  
2    3250.000000  
3    4201.754386  
4    3450.000000  
..           ...  
339  4201.754386  
340  4850.000000  
341  5750.000000  
342  5200.000000  
343  5400.000000  

[344 rows x 6 columns]

In [ ]:
y=df.iloc[:,6:]#dependent variable
y

sex
0      MALE
1    FEMALE
2    FEMALE
3      MALE
4    FEMALE
..      ...
339    MALE
340  FEMALE
341    MALE
342  FEMALE
343    MALE

[344 rows x 1 columns]

# **Performing Encoding process**

In [ ]:
x.head()

species     island  culmen_length_mm  culmen_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen          39.10000         18.70000         181.000000   
1  Adelie  Torgersen          39.50000         17.40000         186.000000   
2  Adelie  Torgersen          40.30000         18.00000         195.000000   
3  Adelie  Torgersen          43.92193         17.15117         200.915205   
4  Adelie  Torgersen          36.70000         19.30000         193.000000   

   body_mass_g  
0  3750.000000  
1  3800.000000  
2  3250.000000  
3  4201.754386  
4  3450.000000

In [ ]:
#to transform categorical variable to numerical we using encoding process
#here we use column transform an one hot encoding technique
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ct=ColumnTransformer([('oh',OneHotEncoder(),[0,1])],remainder='passthrough')

In [ ]:
ct_x=ct.fit_transform(x)

In [ ]:
ct_x

array([[1.00e+00, 0.00e+00, 0.00e+00, ..., 1.87e+01, 1.81e+02, 3.75e+03],
       [1.00e+00, 0.00e+00, 0.00e+00, ..., 1.74e+01, 1.86e+02, 3.80e+03],
       [1.00e+00, 0.00e+00, 0.00e+00, ..., 1.80e+01, 1.95e+02, 3.25e+03],
       ...,
       [0.00e+00, 0.00e+00, 1.00e+00, ..., 1.57e+01, 2.22e+02, 5.75e+03],
       [0.00e+00, 0.00e+00, 1.00e+00, ..., 1.48e+01, 2.12e+02, 5.20e+03],
       [0.00e+00, 0.00e+00, 1.00e+00, ..., 1.61e+01, 2.13e+02, 5.40e+03]])

In [ ]:
# Since the value are not in proper scale we use standard scaler to make the better for prediction
from sklearn.preprocessing import StandardScaler

In [ ]:
ss=StandardScaler()

In [ ]:
ss_x=ss.fit_transform(ct_x)

In [ ]:
ss_x

array([[ 1.12390297, -0.49636359, -0.75075719, ...,  0.78774251,
        -1.42248782, -0.56578921],
       [ 1.12390297, -0.49636359, -0.75075719, ...,  0.12655633,
        -1.06535169, -0.50316788],
       [ 1.12390297, -0.49636359, -0.75075719, ...,  0.43171918,
        -0.42250666, -1.19200251],
       ...,
       [-0.88975652, -0.49636359,  1.33198857, ..., -0.73807176,
         1.50602843,  1.93906399],
       [-0.88975652, -0.49636359,  1.33198857, ..., -1.19581604,
         0.79175618,  1.25022936],
       [-0.88975652, -0.49636359,  1.33198857, ..., -0.53462985,
         0.8631834 ,  1.50071468]])

In [ ]:
#then using label encoding to convert given value to  numerical value
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [ ]:
le_y=le.fit_transform(y)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
le_y

array([2, 1, 1, 2, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 2,
       1, 2, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 2,
       1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2,
       1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1,
       2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2,
       1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2,
       1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 2,
       2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 2,
       1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 1, 1, 2,
       1, 2, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1, 2, 2, 1,
       1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1,
       1, 2, 1, 2, 2, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2,
       2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2,
       2, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 2, 1,

# **Train test spliting**

In [ ]:
# here we split the data into training and testing set
from sklearn.model_selection import train_test_split

In [ ]:
# train size is set to 80% and test size is set to 20%
xtrain,xtest,ytrain,ytest=train_test_split(ss_x,le_y,test_size=0.2,random_state=0)

In [ ]:
print(xtrain.shape)

(275, 10)


In [ ]:
print(ytrain.shape)

(275,)


In [ ]:
print(xtest.shape)

(69, 10)


In [ ]:
print(ytest.shape)

(69,)


# **Model Building**

In [ ]:
# 1st model selected for classification is decision tree
from sklearn.tree import DecisionTreeClassifier

In [ ]:
#criterion entropy condition will determin quality of split from data that is entropy meansmore random
dt=DecisionTreeClassifier(criterion='entropy',random_state=0) #initializing classifier

In [ ]:
dt.fit(xtrain,ytrain) #fitting training set

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:
y_traindt=dt.predict(xtrain)# making prediction on train set

In [ ]:
y_testdt=dt.predict(xtest)# making prediction on test set

In [ ]:
y_traindt

array([2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1,
       1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2,
       2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 0, 1, 2, 1, 2, 2, 2, 1, 2,
       1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2,
       2, 1, 1, 1, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 2,
       1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2,
       1, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 1,
       2, 1, 1, 2, 2, 2, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2,
       1, 2, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1,
       1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2,
       1, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2,
       1, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1])

In [ ]:
ytrain

array([2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1,
       1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2,
       2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 0, 1, 2, 1, 2, 2, 2, 1, 2,
       1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2,
       2, 1, 1, 1, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 2,
       1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2,
       1, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 1,
       2, 1, 1, 2, 2, 2, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2,
       1, 2, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1,
       1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2,
       1, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2,
       1, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1])

In [ ]:
y_testdt

array([1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1,
       2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1,
       2, 2, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 2, 1,
       2, 1, 2])

In [ ]:
ytest

array([2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1,
       2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1,
       2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 2, 1,
       2, 2, 2])

In [ ]:
# 2nd model for classification is GaussianNB
from sklearn.naive_bayes import GaussianNB

In [ ]:
nb=GaussianNB() #initializing classifier

In [ ]:
nb.fit(xtrain,ytrain) #fiting traing set of data

GaussianNB()

In [ ]:
y_trainnb=nb.predict(xtrain) # making prediction on train set

In [ ]:
y_testnb=nb.predict(xtest)# making prediction on test set

In [ ]:
y_trainnb

array([2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 2, 1, 2, 1, 1, 2,
       1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 0, 1, 2, 1, 1, 2, 2, 1, 2,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 1,
       2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1,
       1, 1, 2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 1, 2,
       2, 2, 2, 2, 2, 1, 1, 2, 1, 1, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2,
       1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 2, 2, 1, 2, 1, 1,
       2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 2, 2,
       1, 2, 2, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1,
       1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2,
       1, 2, 2, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 2, 1, 1, 1, 2, 1, 2,
       1, 2, 1, 2, 1, 1, 2, 2, 2, 1, 1])

In [ ]:
ytrain

array([2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1,
       1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2,
       2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 0, 1, 2, 1, 2, 2, 2, 1, 2,
       1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2,
       2, 1, 1, 1, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 2,
       1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2,
       1, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 1,
       2, 1, 1, 2, 2, 2, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2,
       1, 2, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1,
       1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2,
       1, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2,
       1, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1])

In [ ]:
y_testnb

array([1, 2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1,
       2, 1, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 1,
       1, 1, 2])

In [ ]:
ytest

array([2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1,
       2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1,
       2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 2, 1,
       2, 2, 2])

In [ ]:
#3rd  model used for classifiaction is Adaboost classifier
from sklearn.ensemble import AdaBoostClassifier

In [ ]:
a=AdaBoostClassifier() #initializing classifier

In [ ]:
a.fit(xtrain,ytrain) # fitting training set of data

AdaBoostClassifier()

In [ ]:
y_traina=a.predict(xtrain) # making prediction on train set

In [ ]:
y_testa=a.predict(xtest) # making prediction on test set

In [ ]:
y_traina

array([2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1,
       1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2,
       2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 1, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2,
       2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2,
       1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2])

In [ ]:
ytrain

array([2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1,
       1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2,
       2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 0, 1, 2, 1, 2, 2, 2, 1, 2,
       1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2,
       2, 1, 1, 1, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 2,
       1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2,
       1, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 1,
       2, 1, 1, 2, 2, 2, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2,
       1, 2, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1,
       1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2,
       1, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2,
       1, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1])

In [ ]:
y_testa

array([2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 1, 1, 2, 2, 1, 2, 2, 1, 2,
       2, 2, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1,
       2, 1, 2])

In [ ]:
ytest

array([2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1,
       2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1,
       2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 2, 1,
       2, 2, 2])

In [ ]:
# 4th model  we used for classification is randomforestclassifier
from sklearn.ensemble import RandomForestClassifier

In [ ]:
''' random forest classifier() include nestimator which means number of decision tree for estimation
entropy takes care for quality of split
'''

rf=RandomForestClassifier(n_estimators=5,criterion='entropy',random_state=0)

In [ ]:
rf.fit(xtrain,ytrain) #fitting training set of data

RandomForestClassifier(criterion='entropy', n_estimators=5, random_state=0)

In [ ]:
y_trainrf=rf.predict(xtrain) # making prediction on train set

In [ ]:
y_testrf=rf.predict(xtest) # making prediction on test set

In [ ]:
y_trainrf

array([2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1,
       1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2,
       2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 0, 1, 2, 1, 2, 2, 2, 1, 2,
       1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2,
       2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2,
       1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2,
       1, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 2, 2, 2, 1, 2, 1, 1,
       2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2,
       1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1,
       1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2,
       1, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2,
       1, 1, 1, 2, 1, 1, 2, 2, 2, 2, 1])

In [ ]:
ytrain

array([2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1,
       1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2,
       2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 0, 1, 2, 1, 2, 2, 2, 1, 2,
       1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2,
       2, 1, 1, 1, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 2,
       1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2,
       1, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 1,
       2, 1, 1, 2, 2, 2, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2,
       1, 2, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1,
       1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2,
       1, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2,
       1, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1])

In [ ]:
y_testrf

array([1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1,
       2, 2, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 2, 1,
       1, 1, 2])

In [ ]:
ytest

array([2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1,
       2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1,
       2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 2, 1,
       2, 2, 2])

# **Kfold cross validation**

In [ ]:
#here we use k fold to pick best model among chossen
models = {
    'Decision Tree': DecisionTreeClassifier(),
    'naive bayes': GaussianNB(),
    'Ada Boosting ': AdaBoostClassifier(),
    'Random Forest': RandomForestClassifier()
}

In [ ]:
from sklearn.model_selection import cross_val_score
metrics = ['accuracy', 'precision_macro', 'recall_macro', 'f1_macro']
results = {}

for model_name, model in models.items():
    model_results = {}
    for metric in metrics:
        scores = cross_val_score(model, ss_x, le_y, cv=5, scoring=metric)
        model_results[metric] = np.mean(scores)
    results[model_name] = model_results

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined a

In [ ]:
results_df = pd.DataFrame(results)
print(results_df)

                 Decision Tree  naive bayes  Ada Boosting   Random Forest
accuracy              0.770631     0.636360       0.569608       0.851748
precision_macro       0.653150     0.633061       0.399963       0.793143
recall_macro          0.671335     0.590267       0.483752       0.782893
f1_macro              0.644196     0.511408       0.365506       0.783103


In [ ]:
best_model = results_df.mean(axis=0).idxmax()
print(f"\nBest Model from above 4 is  {best_model}")


Best Model from above 4 is  Random Forest


Random forest is the best based on the accuracy precision and many more as random forest combines mutiple decision tree which improves accuracy of the model it also reduces overfitting