In [ ]:
#importing important packages i.e pandas and numpy
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
#reading the data set
df=pd.read_csv('/content/drug200.xls')

In [ ]:
df

Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [ ]:
#checing for first 5 rows from the data set
df.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [ ]:
#checking for null values and dtypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [ ]:
# gives discription about statistic
df.describe()

Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000

In [ ]:
#checking for null values through out the data
df.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [ ]:
df.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [ ]:
''' from preprocessing class we import label encoder to convert
string data or categorical data into numerical'''

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()#initializing LabelEncoder()

df['Sex']=le.fit_transform(df['Sex'])
df['BP']=le.fit_transform(df['BP'])
df['Cholesterol']=le.fit_transform(df['Cholesterol'])
df['Drug']=le.fit_transform(df['Drug'])

In [ ]:
df.head()

Age  Sex  BP  Cholesterol  Na_to_K  Drug
0   23    0   0            0   25.355     0
1   47    1   1            0   13.093     3
2   47    1   1            0   10.114     3
3   28    0   2            0    7.798     4
4   61    0   1            0   18.043     0

In [ ]:
#defining dependent and independent valiable
x=df.iloc[:,0:5] #independent variable
x

Age  Sex  BP  Cholesterol  Na_to_K
0     23    0   0            0   25.355
1     47    1   1            0   13.093
2     47    1   1            0   10.114
3     28    0   2            0    7.798
4     61    0   1            0   18.043
..   ...  ...  ..          ...      ...
195   56    0   1            0   11.567
196   16    1   1            0   12.006
197   52    1   2            0    9.894
198   23    1   2            1   14.020
199   40    0   1            1   11.349

[200 rows x 5 columns]

In [ ]:
y=df.iloc[:,5:].values#dependent variable

In [ ]:
y

array([[0],
       [3],
       [3],
       [4],
       [0],
       [4],
       [0],
       [3],
       [0],
       [0],
       [3],
       [0],
       [0],
       [0],
       [4],
       [0],
       [4],
       [1],
       [3],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [4],
       [0],
       [0],
       [4],
       [2],
       [4],
       [0],
       [4],
       [4],
       [1],
       [4],
       [4],
       [4],
       [0],
       [2],
       [0],
       [4],
       [4],
       [4],
       [1],
       [3],
       [0],
       [0],
       [0],
       [4],
       [0],
       [0],
       [2],
       [3],
       [2],
       [0],
       [4],
       [0],
       [0],
       [1],
       [0],
       [4],
       [2],
       [0],
       [1],
       [4],
       [0],
       [0],
       [2],
       [0],
       [4],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [4],
       [2],
       [4],
       [3],
    

In [ ]:
#using standard scaler to get all the numerical value into a particular range
from sklearn.preprocessing import StandardScaler

In [ ]:
ss=StandardScaler() #initializing the StandardScaler()

In [ ]:
s_x=ss.fit_transform(x)

In [ ]:
s_x

array([[-1.29159102, -1.040833  , -1.11016894, -0.97043679,  1.28652212],
       [ 0.16269866,  0.96076892,  0.10979693, -0.97043679, -0.4151454 ],
       [ 0.16269866,  0.96076892,  0.10979693, -0.97043679, -0.82855818],
       [-0.988614  , -1.040833  ,  1.32976279, -0.97043679, -1.14996267],
       [ 1.0110343 , -1.040833  ,  0.10979693, -0.97043679,  0.27179427],
       [-1.35218642, -1.040833  ,  1.32976279, -0.97043679, -1.03769314],
       [ 0.28388946, -1.040833  ,  1.32976279, -0.97043679,  0.02643885],
       [-0.20087376,  0.96076892,  0.10979693, -0.97043679, -0.70046821],
       [ 0.9504389 ,  0.96076892,  1.32976279, -0.97043679, -0.12676951],
       [-0.07968296,  0.96076892,  0.10979693,  1.03046381,  0.45567206],
       [ 0.16269866, -1.040833  ,  0.10979693, -0.97043679, -0.59916196],
       [-0.62504158, -1.040833  , -1.11016894,  1.03046381,  0.43221897],
       [-0.07968296,  0.96076892,  0.10979693, -0.97043679, -0.09832049],
       [ 1.79877454, -1.040833  ,  0.1

In [ ]:
# spliting dataset into training and testing set for model building
from sklearn.model_selection import train_test_split

In [ ]:
'''declaring training and testing variable with test size
as 30% where as training size will be 70% also we set ,
random state to 42 for more entropy through out the data'''

xtrain,xtest,ytrain,ytest=train_test_split(s_x,y,test_size=0.3,random_state=42)

In [ ]:
x.shape

(200, 5)

In [ ]:
y.shape

(200, 1)

In [ ]:
#using tenser flow to built ANN model

'''here import sequential and dense from models and layars(class)
to add layers to ANN model'''

from tensorflow.keras.models import Sequential

In [ ]:
from tensorflow.keras.layers import Dense

In [ ]:
ann=Sequential()#initializing Sequential()

In [ ]:
ann.add(Dense(5,activation='relu',kernel_initializer='random_uniform')) #input layer

In [ ]:
# Three hidden layers

ann.add(Dense(10,activation='relu',kernel_initializer='random_uniform'))
ann.add(Dense(15,activation='relu',kernel_initializer='random_uniform'))
ann.add(Dense(20,activation='relu',kernel_initializer='random_uniform'))

In [ ]:
#output layers
ann.add(Dense(5,activation='softmax',kernel_initializer='random_uniform')) #\

In [ ]:
#copiling model with optimizer as adam and metrics set to accuracy
ann.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [ ]:
#here we fit the  model onto training set
ann.fit(xtrain,ytrain,batch_size=30,epochs=400)

Epoch 1/400
5/5 [==============================] - 1s 8ms/step - loss: 1.6083 - accuracy: 0.4286
Epoch 2/400
5/5 [==============================] - 0s 5ms/step - loss: 1.6049 - accuracy: 0.4643
Epoch 3/400
5/5 [==============================] - 0s 6ms/step - loss: 1.6018 - accuracy: 0.4643
Epoch 4/400
5/5 [==============================] - 0s 5ms/step - loss: 1.5980 - accuracy: 0.4643
Epoch 5/400
5/5 [==============================] - 0s 6ms/step - loss: 1.5943 - accuracy: 0.4643
Epoch 6/400
5/5 [==============================] - 0s 5ms/step - loss: 1.5899 - accuracy: 0.4643
Epoch 7/400
5/5 [==============================] - 0s 4ms/step - loss: 1.5854 - accuracy: 0.4643
Epoch 8/400
5/5 [==============================] - 0s 5ms/step - loss: 1.5803 - accuracy: 0.4643
Epoch 9/400
5/5 [==============================] - 0s 4ms/step - loss: 1.5742 - accuracy: 0.4643
Epoch 10/400
5/5 [==============================] - 0s 4ms/step - loss: 1.5676 - accuracy: 0.4643
Epoch 11/400
5/5 [===========

In [ ]:
#here we made prediction on xtest split of data set and predict y test
pred=ann.predict(xtest)

2/2 [==============================] - 0s 5ms/step


In [ ]:
pred

array([[1.69158389e-04, 3.25595315e-11, 1.98357071e-07, 2.50873920e-02,
        9.74743128e-01],
       [9.99871492e-01, 0.00000000e+00, 0.00000000e+00, 4.95495042e-18,
        1.28535496e-04],
       [7.84895848e-03, 1.21991053e-22, 2.92871298e-15, 1.15758066e-05,
        9.92139459e-01],
       [7.92794344e-06, 2.65382096e-05, 3.55353579e-03, 9.48849380e-01,
        4.75626551e-02],
       [9.99999940e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [9.99999940e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.67451680e-17],
       [9.99999940e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [9.96217947e-04, 6.17197505e-17, 2.16291152e-11, 4.77624679e-04,
        9.98526037e-01],
       [4.40017078e-10, 5.50943136e-01, 4.42903638e-01, 6.15269504e-03,
        6.33785078e-07],
       [1.99837834e-02, 2.97783257e-25, 4.93959936e-17, 2.09283667e-06,
        9.80014086e-01],
       [2.52850879e-10, 6.1455

In [ ]:
ytest

array([[4],
       [0],
       [4],
       [3],
       [0],
       [0],
       [0],
       [4],
       [1],
       [4],
       [1],
       [4],
       [0],
       [1],
       [2],
       [0],
       [2],
       [4],
       [3],
       [0],
       [2],
       [4],
       [4],
       [0],
       [0],
       [0],
       [3],
       [4],
       [0],
       [4],
       [0],
       [3],
       [3],
       [0],
       [1],
       [0],
       [4],
       [1],
       [0],
       [1],
       [4],
       [4],
       [4],
       [0],
       [0],
       [3],
       [0],
       [0],
       [0],
       [4],
       [4],
       [0],
       [4],
       [0],
       [4],
       [0],
       [1],
       [0],
       [0],
       [0]])

**Testing model on random data **

In [ ]:
pred[0]

array([1.6915839e-04, 3.2559531e-11, 1.9835707e-07, 2.5087392e-02,
       9.7474313e-01], dtype=float32)

In [ ]:
ytest[0]

array([4])

In [ ]:
test1=np.argmax(pred[0])

In [ ]:
test1

4

In [ ]:
pred[20]

array([2.9728073e-09, 3.9791250e-01, 5.7655388e-01, 2.5528390e-02,
       5.1556053e-06], dtype=float32)

In [ ]:
ytest[20]

array([2])

In [ ]:
test2=np.argmax(pred[20])

In [ ]:
test2

2